/**
 * Sentry.io configuration for Next.js 15
 * 
 * This file is automatically generated by the Sentry wizard.
 * Manual modifications may be lost if the wizard is run again.
 */

import * as Sentry from "@sentry/nextjs";

Sentry.init({
  dsn: process.env.NEXT_PUBLIC_SENTRY_DSN,
  environment: process.env.NODE_ENV || "development",
  
  // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
  // We recommend adjusting this value in production
  tracesSampleRate: process.env.NODE_ENV === "production" ? 0.1 : 1.0,

  // Capture Replay for 10% of all sessions,
  // plus, capture 100% of sessions with an error
  replaysSessionSampleRate: 0.1,
  replaysOnErrorSampleRate: 1.0,

  // Do not capture localhost errors in development
  ignoreErrors: [
    // Network errors
    "Network error",
    "Failed to fetch",
    "NetworkError",
    
    // Noisy browser errors
    "ResizeObserver loop limit exceeded",
    "Non-Error promise rejection captured",
    
    // Chrome extension errors
    "chrome-extension://",
    "moz-extension://",
  ],
});

export { Sentry };
