import {
  HardHatIcon as HardHat,
  ChefHatIcon as ChefHat,
  LockIcon as Lock,
  FlameIcon as Flame,
  CigaretteIcon as Cigarette,
  DropletsIcon as Droplets,
  UsersIcon as Users,
  ActivityIcon as Activity,
  TrendingUpIcon as TrendingUp,
  UserCheckIcon as UserCheck,
  ScanFaceIcon as ScanFace,
  AlignJustifyIcon as AlignJustify,
  ClockIcon as Clock,
  CreditCardIcon as CreditCard,
  UtensilsCrossedIcon as UtensilsCrossed,
  CoffeeIcon as Coffee,
  TruckIcon as Truck,
  CarIcon as Car,
  ReceiptIcon as Receipt,
  SandwichIcon as Sandwich,
  NavigationIcon as Navigation,
  IdCardIcon as IdCard,
  EyeIcon as Eye,
  RadioIcon as Radio,
  BoxIcon as Box,
  AlertOctagonIcon as AlertOctagon,
  PersonStandingIcon as PersonStanding,
  SearchPersonIcon as Search,
  BusIcon as Bus,
} from "@/components/ai-service-icons";
import type { AIServiceMeta } from "./AIServiceDetailView";

export const ALL_SERVICES: AIServiceMeta[] = [
  // ── Safety ──────────────────────────────────────────────────────────────
  {
    id: "helmet-detection",
    apiId: 13,
    label: "Helmet Detection",
    category: "Safety",
    categoryHref: "/dashboard/ai-services?tab=safety",
    color: "#ef4444",
    bgColor: "#fef2f2",
    icon: HardHat,
    description: "Detect workers not wearing safety helmets on site.",
    detailedDescription:
      "Real-time AI analysis of video feeds to identify individuals not wearing required safety helmets. Instantly alerts supervisors and logs violations for compliance reporting.",
    useCases: [
      "Construction site safety enforcement",
      "Industrial facility PPE compliance",
      "Automated violation reporting",
      "Insurance & audit documentation",
    ],
    stats: {
      totalDetections: 14832,
      todayDetections: 47,
      accuracy: 97,
      uptime: 99.8,
      avgResponseMs: 42,
      cameras: 8,
    },
  },
  {
    id: "kitchen-ppe",
    apiId: 14,
    label: "Kitchen PPE",
    category: "Safety",
    categoryHref: "/dashboard/ai-services?tab=safety",
    color: "#ef4444",
    bgColor: "#fef2f2",
    icon: ChefHat,
    description: "Ensure kitchen staff wear required protective equipment.",
    detailedDescription:
      "Monitors kitchen cameras to verify that all staff are wearing proper PPE including gloves, hairnets, and aprons before and during food preparation to meet health regulations.",
    useCases: [
      "Restaurant health code compliance",
      "Food safety auditing",
      "Real-time staff alerts",
      "Regulatory inspection preparation",
    ],
    stats: {
      totalDetections: 9274,
      todayDetections: 31,
      accuracy: 95,
      uptime: 99.5,
      avgResponseMs: 55,
      cameras: 5,
    },
  },
  {
    id: "restricted-area",
    apiId: 24,
    label: "Restricted Area",
    category: "Safety",
    categoryHref: "/dashboard/ai-services?tab=safety",
    color: "#ef4444",
    bgColor: "#fef2f2",
    icon: Lock,
    description: "Alert when unauthorized personnel enter restricted zones.",
    detailedDescription:
      "Defines virtual perimeters around sensitive or dangerous areas and triggers instant alerts whenever unauthorized individuals cross the boundary.",
    useCases: [
      "Server room & data center security",
      "Hazardous machinery zones",
      "Executive-only areas",
      "Stockroom access control",
    ],
    stats: {
      totalDetections: 3210,
      todayDetections: 12,
      accuracy: 98,
      uptime: 99.9,
      avgResponseMs: 38,
      cameras: 6,
    },
  },
  {
    id: "smoke-fire",
    apiId: 11,
    label: "Smoke & Fire",
    category: "Safety",
    categoryHref: "/dashboard/ai-services?tab=safety",
    color: "#ef4444",
    bgColor: "#fef2f2",
    icon: Flame,
    description: "Early detection of smoke and fire events.",
    detailedDescription:
      "Uses computer vision to detect visual signatures of smoke and flames earlier than traditional sensors, enabling faster emergency response and reducing false alarms.",
    useCases: [
      "Warehouse fire early-warning",
      "Kitchen fire suppression triggers",
      "Outdoor area monitoring",
      "Backup to smoke detectors",
    ],
    stats: {
      totalDetections: 421,
      todayDetections: 2,
      accuracy: 96,
      uptime: 99.99,
      avgResponseMs: 28,
      cameras: 12,
    },
  },
  {
    id: "smoking-detection",
    apiId: 26,
    label: "Smoking Detection",
    category: "Safety",
    categoryHref: "/dashboard/ai-services?tab=safety",
    color: "#ef4444",
    bgColor: "#fef2f2",
    icon: Cigarette,
    description: "Identify smoking in no-smoking zones automatically.",
    detailedDescription:
      "Detects the act of smoking from camera footage and sends immediate alerts to enforce no-smoking policies in workplaces, restaurants, and public areas.",
    useCases: [
      "Workplace policy enforcement",
      "Restaurant & hospitality compliance",
      "Hospital campus monitoring",
      "Legal liability protection",
    ],
    stats: {
      totalDetections: 6847,
      todayDetections: 24,
      accuracy: 93,
      uptime: 99.2,
      avgResponseMs: 60,
      cameras: 7,
    },
  },
  {
    id: "spill-detection",
    apiId: 27,
    label: "Spill Detection",
    category: "Safety",
    categoryHref: "/dashboard/ai-services?tab=safety",
    color: "#ef4444",
    bgColor: "#fef2f2",
    icon: Droplets,
    description: "Detect liquid spills before they cause accidents.",
    detailedDescription:
      "Continuously monitors floors for liquid spills or wet surfaces and alerts cleaning staff immediately to prevent slip-and-fall accidents and contamination.",
    useCases: [
      "Grocery & retail floor safety",
      "Restaurant kitchen monitoring",
      "Warehouse accident prevention",
      "Food processing compliance",
    ],
    stats: {
      totalDetections: 5512,
      todayDetections: 18,
      accuracy: 91,
      uptime: 98.9,
      avgResponseMs: 72,
      cameras: 9,
    },
  },

  // ── Analytics ────────────────────────────────────────────────────────────
  {
    id: "age-gender",
    apiId: 1,
    label: "Age Gender Analytics",
    category: "Analytics",
    categoryHref: "/dashboard/ai-services?tab=analytics",
    color: "#3b82f6",
    bgColor: "#eff6ff",
    icon: Users,
    description: "Analyze visitor demographics in real-time.",
    detailedDescription:
      "Estimates the age range and gender of visitors passing through camera zones to provide demographic insights for marketing, staffing, and store layout decisions.",
    useCases: [
      "Retail demographic profiling",
      "Targeted in-store promotions",
      "Staffing optimization by shift",
      "Marketing campaign validation",
    ],
    stats: {
      totalDetections: 82341,
      todayDetections: 1790,
      accuracy: 89,
      uptime: 99.1,
      avgResponseMs: 65,
      cameras: 14,
    },
  },
  {
    id: "behavior-analysis",
    apiId: 3,
    label: "Behavior Analysis",
    category: "Analytics",
    categoryHref: "/dashboard/ai-services?tab=analytics",
    color: "#3b82f6",
    bgColor: "#eff6ff",
    icon: Activity,
    description: "Understand customer behavior and movement patterns.",
    detailedDescription:
      "Tracks and analyzes customer movement paths, dwell times, and interaction hotspots to optimize store layouts and identify areas of high and low engagement.",
    useCases: [
      "Store layout optimization",
      "Product placement strategy",
      "Queue behavior analysis",
      "Staff-customer interaction insights",
    ],
    stats: {
      totalDetections: 41230,
      todayDetections: 876,
      accuracy: 88,
      uptime: 98.7,
      avgResponseMs: 88,
      cameras: 11,
    },
  },
  {
    id: "customer-traffic",
    apiId: 7,
    label: "Customer Traffic",
    category: "Analytics",
    categoryHref: "/dashboard/ai-services?tab=analytics",
    color: "#3b82f6",
    bgColor: "#eff6ff",
    icon: TrendingUp,
    description: "Count and track customer foot traffic trends.",
    detailedDescription:
      "Provides accurate bi-directional foot traffic counting across entry/exit points with hourly and daily trend reports for staffing and capacity planning.",
    useCases: [
      "Peak hour capacity planning",
      "Conversion rate analysis",
      "Multi-branch comparison",
      "Lease renegotiation data",
    ],
    stats: {
      totalDetections: 128502,
      todayDetections: 2802,
      accuracy: 97,
      uptime: 99.6,
      avgResponseMs: 35,
      cameras: 6,
    },
  },
  {
    id: "face-attendance",
    apiId: 2,
    label: "Face Attendance",
    category: "Analytics",
    categoryHref: "/dashboard/ai-services?tab=analytics",
    color: "#3b82f6",
    bgColor: "#eff6ff",
    icon: UserCheck,
    description: "Automate attendance tracking via facial recognition.",
    detailedDescription:
      "Replaces manual clock-in systems with touchless facial recognition attendance, logging employee entry/exit times automatically and integrating with HR payroll systems.",
    useCases: [
      "Touchless employee clock-in",
      "Payroll integration",
      "Overtime & shift tracking",
      "Remote site workforce management",
    ],
    stats: {
      totalDetections: 34120,
      todayDetections: 142,
      accuracy: 99,
      uptime: 99.8,
      avgResponseMs: 40,
      cameras: 4,
    },
  },
  {
    id: "face-detection",
    apiId: 10,
    label: "Face Detection",
    category: "Analytics",
    categoryHref: "/dashboard/ai-services?tab=analytics",
    color: "#3b82f6",
    bgColor: "#eff6ff",
    icon: ScanFace,
    description: "Detect and identify faces across camera feeds.",
    detailedDescription:
      "Core face detection engine that identifies the presence and location of human faces in video streams, powering downstream analytics like demographics and attendance.",
    useCases: [
      "VIP customer recognition",
      "Repeat visitor tracking",
      "Security watchlist matching",
      "Engagement heatmaps",
    ],
    stats: {
      totalDetections: 91042,
      todayDetections: 2100,
      accuracy: 98,
      uptime: 99.7,
      avgResponseMs: 33,
      cameras: 16,
    },
  },
  {
    id: "queue-management",
    apiId: 22,
    label: "Queue Management",
    category: "Analytics",
    categoryHref: "/dashboard/ai-services?tab=analytics",
    color: "#3b82f6",
    bgColor: "#eff6ff",
    icon: AlignJustify,
    description: "Monitor queue lengths and optimize service flow.",
    detailedDescription:
      "Measures real-time queue lengths and wait times at service points, alerting managers when thresholds are exceeded and providing historical data to improve staffing schedules.",
    useCases: [
      "Checkout queue optimization",
      "Service desk management",
      "SLA compliance monitoring",
      "Staffing schedule refinement",
    ],
    stats: {
      totalDetections: 28740,
      todayDetections: 634,
      accuracy: 94,
      uptime: 99.3,
      avgResponseMs: 50,
      cameras: 8,
    },
  },
  {
    id: "waiting-customer",
    apiId: 29,
    label: "Waiting Customer",
    category: "Analytics",
    categoryHref: "/dashboard/ai-services?tab=analytics",
    color: "#3b82f6",
    bgColor: "#eff6ff",
    icon: Clock,
    description: "Track customers waiting and alert when thresholds exceed.",
    detailedDescription:
      "Specifically tracks stationary customers waiting for service, measuring dwell time and triggering staff alerts when waiting periods exceed configured thresholds to improve satisfaction.",
    useCases: [
      "Customer satisfaction improvement",
      "Staff alert automation",
      "Waiting area capacity",
      "SLA enforcement",
    ],
    stats: {
      totalDetections: 18230,
      todayDetections: 160,
      accuracy: 92,
      uptime: 99.0,
      avgResponseMs: 58,
      cameras: 5,
    },
  },

  // ── Operations ───────────────────────────────────────────────────────────
  {
    id: "cash-register",
    apiId: 4,
    label: "Cash Register",
    category: "Operations",
    categoryHref: "/dashboard/ai-services?tab=operations",
    color: "#f59e0b",
    bgColor: "#fffbeb",
    icon: CreditCard,
    description: "Monitor cash register and detect unusual activity.",
    detailedDescription:
      "Monitors cash register areas with AI to detect suspicious behaviour such as skimming, no-receipt transactions, open till without transaction, or unauthorized access to cash drawers.",
    useCases: [
      "Theft & fraud prevention",
      "Cashier behaviour auditing",
      "Compliance monitoring",
      "Loss prevention reporting",
    ],
    stats: {
      totalDetections: 7823,
      todayDetections: 89,
      accuracy: 95,
      uptime: 99.4,
      avgResponseMs: 45,
      cameras: 5,
    },
  },
  {
    id: "clean-tables",
    apiId: 5,
    label: "Clean Tables",
    category: "Operations",
    categoryHref: "/dashboard/ai-services?tab=operations",
    color: "#f59e0b",
    bgColor: "#fffbeb",
    icon: UtensilsCrossed,
    description: "Detect dirty tables and notify cleaning staff.",
    detailedDescription:
      "Automatically identifies tables that have not been cleared after customers leave, notifying cleaning staff in real-time to reduce turnaround time and improve guest experience.",
    useCases: [
      "Restaurant table turnover",
      "Hotel lobby maintenance",
      "Food court management",
      "Cleaning staff task routing",
    ],
    stats: {
      totalDetections: 22341,
      todayDetections: 1,
      accuracy: 92,
      uptime: 98.8,
      avgResponseMs: 68,
      cameras: 6,
    },
  },
  {
    id: "cup-counting",
    apiId: 6,
    label: "Cup Counting",
    category: "Operations",
    categoryHref: "/dashboard/ai-services?tab=operations",
    color: "#f59e0b",
    bgColor: "#fffbeb",
    icon: Coffee,
    description: "Count cups to track usage and manage inventory.",
    detailedDescription:
      "Uses computer vision to count disposable cups and beverage containers in real-time on production lines or dispensing areas for accurate inventory control and waste reduction.",
    useCases: [
      "Beverage inventory tracking",
      "Waste reduction programs",
      "Supplier order automation",
      "Usage vs sales reconciliation",
    ],
    stats: {
      totalDetections: 58234,
      todayDetections: 927,
      accuracy: 96,
      uptime: 99.5,
      avgResponseMs: 30,
      cameras: 4,
    },
  },
  {
    id: "delivery-tracking",
    apiId: 8,
    label: "Delivery Tracking",
    category: "Operations",
    categoryHref: "/dashboard/ai-services?tab=operations",
    color: "#f59e0b",
    bgColor: "#fffbeb",
    icon: Truck,
    description: "Track delivery vehicles and personnel arrival.",
    detailedDescription:
      "Monitors loading docks and delivery areas to log arrival and departure times of delivery vehicles and personnel, providing an automated record for logistics and scheduling.",
    useCases: [
      "Delivery SLA verification",
      "Loading dock scheduling",
      "Vendor accountability",
      "Cold-chain timing compliance",
    ],
    stats: {
      totalDetections: 9124,
      todayDetections: 43,
      accuracy: 97,
      uptime: 99.6,
      avgResponseMs: 40,
      cameras: 3,
    },
  },
  {
    id: "drive-thru",
    apiId: 9,
    label: "Drive Thru",
    category: "Operations",
    categoryHref: "/dashboard/ai-services?tab=operations",
    color: "#f59e0b",
    bgColor: "#fffbeb",
    icon: Car,
    description: "Monitor drive-thru queues and service times.",
    detailedDescription:
      "Tracks vehicles in the drive-thru lane from arrival to departure, measuring service time at each station and providing analytics to reduce wait times and improve throughput.",
    useCases: [
      "Fast-food service time optimization",
      "Staff performance measurement",
      "Peak hour staffing planning",
      "Customer experience improvement",
    ],
    stats: {
      totalDetections: 31450,
      todayDetections: 512,
      accuracy: 95,
      uptime: 99.3,
      avgResponseMs: 52,
      cameras: 4,
    },
  },
  {
    id: "receipt-detection",
    apiId: 23,
    label: "Receipt Detection",
    category: "Operations",
    categoryHref: "/dashboard/ai-services?tab=operations",
    color: "#f59e0b",
    bgColor: "#fffbeb",
    icon: Receipt,
    description: "Verify receipt printing and handover at checkout.",
    detailedDescription:
      "Ensures that receipts are printed and handed to customers at point-of-sale, flagging incidents where the handover step is skipped to reduce disputes and ensure compliance.",
    useCases: [
      "POS compliance auditing",
      "Customer dispute reduction",
      "Cashier process verification",
      "Tax compliance documentation",
    ],
    stats: {
      totalDetections: 44210,
      todayDetections: 724,
      accuracy: 93,
      uptime: 99.1,
      avgResponseMs: 38,
      cameras: 5,
    },
  },
  {
    id: "sandwich-counting",
    apiId: 25,
    label: "Sandwich Counting",
    category: "Operations",
    categoryHref: "/dashboard/ai-services?tab=operations",
    color: "#f59e0b",
    bgColor: "#fffbeb",
    icon: Sandwich,
    description: "Count food items on production line for quality control.",
    detailedDescription:
      "Monitors food assembly lines to count and verify each food item such as sandwiches, burgers, or wraps, flagging incomplete orders and providing production throughput metrics.",
    useCases: [
      "QC on food assembly lines",
      "Order accuracy verification",
      "Production rate tracking",
      "Waste and error reduction",
    ],
    stats: {
      totalDetections: 76340,
      todayDetections: 1834,
      accuracy: 94,
      uptime: 99.4,
      avgResponseMs: 35,
      cameras: 6,
    },
  },

  // ── Monitoring ──────────────────────────────────────────────────────────
  {
    id: "gate-monitoring",
    apiId: 12,
    label: "Gate Monitoring",
    category: "Monitoring",
    categoryHref: "/dashboard/ai-services?tab=monitoring",
    color: "#10b981",
    bgColor: "#ecfdf5",
    icon: Navigation,
    description: "Monitor entry and exit gates for unauthorized access.",
    detailedDescription:
      "Provides 24/7 AI surveillance of gates, turnstiles, and access points, detecting tailgating, forced entry, or unauthorised passage and triggering immediate security alerts.",
    useCases: [
      "Perimeter security",
      "Tailgating prevention",
      "Access log automation",
      "After-hours intrusion detection",
    ],
    stats: {
      totalDetections: 12840,
      todayDetections: 214,
      accuracy: 98,
      uptime: 99.9,
      avgResponseMs: 30,
      cameras: 8,
    },
  },
  {
    id: "license-plate",
    apiId: 15,
    label: "License Plate",
    category: "Monitoring",
    categoryHref: "/dashboard/ai-services?tab=monitoring",
    color: "#10b981",
    bgColor: "#ecfdf5",
    icon: IdCard,
    description: "Recognize and log vehicle license plates.",
    detailedDescription:
      "Automatically reads and logs license plate numbers from vehicles entering or exiting premises, enabling access control, parking management, and security investigations.",
    useCases: [
      "Parking access control",
      "Delivery vehicle verification",
      "VIP vehicle recognition",
      "Security incident investigations",
    ],
    stats: {
      totalDetections: 38124,
      todayDetections: 821,
      accuracy: 99,
      uptime: 99.8,
      avgResponseMs: 28,
      cameras: 6,
    },
  },
  {
    id: "mask-detection",
    apiId: 16,
    label: "Mask Detection",
    category: "Monitoring",
    categoryHref: "/dashboard/ai-services?tab=monitoring",
    color: "#10b981",
    bgColor: "#ecfdf5",
    icon: Eye,
    description: "Verify face mask compliance in required areas.",
    detailedDescription:
      "Detects whether individuals in monitored areas are wearing face masks correctly, supporting health policy compliance in medical facilities, food production areas, and regulated workplaces.",
    useCases: [
      "Hospital & clinic compliance",
      "Food prep area monitoring",
      "Clean-room access control",
      "Health policy enforcement",
    ],
    stats: {
      totalDetections: 54320,
      todayDetections: 1120,
      accuracy: 96,
      uptime: 99.5,
      avgResponseMs: 42,
      cameras: 10,
    },
  },
  {
    id: "motion-detection",
    apiId: 17,
    label: "Motion Detection",
    category: "Monitoring",
    categoryHref: "/dashboard/ai-services?tab=monitoring",
    color: "#10b981",
    bgColor: "#ecfdf5",
    icon: Radio,
    description: "Detect movement in monitored areas and trigger alerts.",
    detailedDescription:
      "AI-powered motion detection that distinguishes meaningful motion events from noise, reducing false alarms and providing clip-based evidence for security events.",
    useCases: [
      "After-hours intrusion alerts",
      "Parking lot surveillance",
      "Server room access monitoring",
      "Evidence clip generation",
    ],
    stats: {
      totalDetections: 28410,
      todayDetections: 390,
      accuracy: 97,
      uptime: 99.9,
      avgResponseMs: 22,
      cameras: 18,
    },
  },
  {
    id: "object-detection",
    apiId: 18,
    label: "Object Detection",
    category: "Monitoring",
    categoryHref: "/dashboard/ai-services?tab=monitoring",
    color: "#10b981",
    bgColor: "#ecfdf5",
    icon: Box,
    description: "Identify and track specific objects in camera feeds.",
    detailedDescription:
      "General-purpose object detection engine that can identify hundreds of object categories, from packages left unattended to equipment out of place, in any monitored environment.",
    useCases: [
      "Unattended package detection",
      "Equipment placement auditing",
      "Asset tracking",
      "Shoplifting item detection",
    ],
    stats: {
      totalDetections: 31240,
      todayDetections: 560,
      accuracy: 93,
      uptime: 99.2,
      avgResponseMs: 55,
      cameras: 12,
    },
  },
  {
    id: "overcrowd-violation",
    apiId: 19,
    label: "Overcrowd Violation",
    category: "Monitoring",
    categoryHref: "/dashboard/ai-services?tab=monitoring",
    color: "#10b981",
    bgColor: "#ecfdf5",
    icon: AlertOctagon,
    description: "Alert when area occupancy exceeds safe capacity.",
    detailedDescription:
      "Counts people in defined zones and triggers alerts when crowd density exceeds safe or regulatory limits, enabling proactive crowd management and compliance.",
    useCases: [
      "Venue capacity compliance",
      "Emergency evacuation planning",
      "Social distancing enforcement",
      "Event management",
    ],
    stats: {
      totalDetections: 4821,
      todayDetections: 34,
      accuracy: 95,
      uptime: 99.6,
      avgResponseMs: 48,
      cameras: 8,
    },
  },
  {
    id: "people-counting",
    apiId: 20,
    label: "People Counting",
    category: "Monitoring",
    categoryHref: "/dashboard/ai-services?tab=monitoring",
    color: "#10b981",
    bgColor: "#ecfdf5",
    icon: PersonStanding,
    description: "Count people in zones for occupancy management.",
    detailedDescription:
      "Provides accurate real-time and historical counts of people in defined areas, supporting occupancy limits, safety compliance, and operational planning across any facility type.",
    useCases: [
      "Building occupancy management",
      "Retail footfall analytics",
      "Public space capacity",
      "Emergency muster counting",
    ],
    stats: {
      totalDetections: 98210,
      todayDetections: 2140,
      accuracy: 98,
      uptime: 99.7,
      avgResponseMs: 32,
      cameras: 14,
    },
  },
  {
    id: "person-detection",
    apiId: 21,
    label: "Person Detection",
    category: "Monitoring",
    categoryHref: "/dashboard/ai-services?tab=monitoring",
    color: "#10b981",
    bgColor: "#ecfdf5",
    icon: Search,
    description: "Detect human presence in monitored areas.",
    detailedDescription:
      "Core human detection model that identifies the presence of people in any scene, serving as the foundation for security alerts, occupancy monitoring, and downstream analytics.",
    useCases: [
      "After-hours presence alerts",
      "Perimeter security",
      "Empty area detection",
      "Occupancy automation triggers",
    ],
    stats: {
      totalDetections: 142000,
      todayDetections: 3100,
      accuracy: 99,
      uptime: 99.9,
      avgResponseMs: 25,
      cameras: 20,
    },
  },
  {
    id: "vehicle-tracking",
    apiId: 28,
    label: "Vehicle Tracking",
    category: "Monitoring",
    categoryHref: "/dashboard/ai-services?tab=monitoring",
    color: "#10b981",
    bgColor: "#ecfdf5",
    icon: Bus,
    description: "Track vehicle movement across camera zones.",
    detailedDescription:
      "Tracks vehicles as they move between camera zones within a facility, providing path analysis, dwell time data, and movement history for logistics and security purposes.",
    useCases: [
      "Logistics yard management",
      "Fleet movement auditing",
      "Parking enforcement",
      "Security incident reconstruction",
    ],
    stats: {
      totalDetections: 24810,
      todayDetections: 420,
      accuracy: 96,
      uptime: 99.5,
      avgResponseMs: 45,
      cameras: 10,
    },
  },
];

export const SERVICE_MAP = Object.fromEntries(
  ALL_SERVICES.map((s) => [s.id, s])
);
